baseURL = 'https://example.com/'
theme = 'hugo-book'
publishDir = 'docs'
defaultContentLanguage = 'ua'

[languages]
[languages.ua]
  languageName = 'Українська'
  contentDir = 'content\ua'
  title = 'Співбесіда: Запитання по JavaScript'
  weight = 1

[languages.en]
  languageName = 'English'
  contentDir = 'content\en'
  title = 'Interview: JavaScript Questions'
  weight = 2

[languages.ru]
  languageName = 'Русский'
  contentDir = 'content\ru'
  title = 'Собеседование: Вопросы по JavaScript'
  weight = 3

[params]
  BookSection = '*'
  BookSearch = false